{% set name = "albumentations" %}
{% set version = "1.4.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afc6caeba7eaf3c4e1128b2d9ff4475b03d1833f2f52f47a7e53a07afd5f72cc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.24.4,<2
    - scipy >=1.10.0
    - scikit-image >=0.21.0
    - pyyaml
    - opencv >=4.9.0.80
    - albucore >=0.0.13
    - pydantic >=2.7.0
    - typing-extensions >=4.9.0
    - eval-type-backport

test:
  imports:
    - albumentations

about:
  home: https://github.com/albu/albumentations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast image augmentation library and easy to use wrapper around other libraries

  doc_url: https://albumentations.readthedocs.io/
  dev_url: https://github.com/albu/albumentations

extra:
  recipe-maintainers:
    - mdraw
    - albu
    - creafz
    - nrweir
    - ternaus
    - BloodAxe
