{% set name = "albumentations" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e9c8a0b54c4182e39576200092564913f6dca7a67ca5aec9bdaa80b8bef93c24

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - imgaug
    - pyyaml
    - opencv

test:
  imports:
    - albumentations

about:
  home: https://github.com/albu/albumentations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast image augmentation library and easy to use wrapper around other libraries

  doc_url: https://albumentations.readthedocs.io/
  dev_url: https://github.com/albu/albumentations

extra:
  recipe-maintainers:
    - mdraw
    - albu
    - creafz
    - nrweir
    - ternaus
    - BloodAxe
