{% set name = "albumentations" %}
{% set version = "1.4.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 739e96afcd1065b3804a6d621b2a95dfec560010a83a2e55c39ba307bdd59f41

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.24.4,<2
    - scipy >=1.10.0
    - scikit-image >=0.21.0
    - pyyaml
    - qudida >=0.0.4
    - opencv >=4.9.0
    - albucore >=0.0.11
    - pydantic >=2.7.0
    - scikit-learn >=1.3.2
    - typing-extensions>=4.9.0

test:
  imports:
    - albumentations

about:
  home: https://github.com/albu/albumentations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast image augmentation library and easy to use wrapper around other libraries

  doc_url: https://albumentations.readthedocs.io/
  dev_url: https://github.com/albu/albumentations

extra:
  recipe-maintainers:
    - mdraw
    - albu
    - creafz
    - nrweir
    - ternaus
    - BloodAxe
