{% set name = "albumentations" %}
{% set version = "1.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 701a9405f059f761f00ce00e187954d01276bdb78b33abcf864e79727db3bf1a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.24.4
    - scipy >=1.10.0
    - scikit-image >=0.21.0
    - pyyaml
    - opencv >=4.9.0
    # https://github.com/albumentations-team/albumentations/issues/1946
    - albucore ==0.0.17
    - pydantic >=2.7.0
    - typing-extensions >=4.9.0
    - eval-type-backport

test:
  requires:
    - python {{ python_min }}
  imports:
    - albumentations

about:
  home: https://github.com/albu/albumentations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast image augmentation library and easy to use wrapper around other libraries

  doc_url: https://albumentations.readthedocs.io/
  dev_url: https://github.com/albu/albumentations

extra:
  recipe-maintainers:
    - mukhery
    - mdraw
    - albu
    - creafz
    - ternaus
    - BloodAxe
