{% set name = "albumentations" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be1af36832c8893314f2a5550e8ac19801e04770734c1b70fa3c996b41f37bed

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.11.1
    - scipy
    - scikit-image >=0.16.1
    - pyyaml
    - qudida >=0.0.4
    - opencv >=4.1.1

test:
  imports:
    - albumentations

about:
  home: https://github.com/albu/albumentations
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast image augmentation library and easy to use wrapper around other libraries

  doc_url: https://albumentations.readthedocs.io/
  dev_url: https://github.com/albu/albumentations

extra:
  recipe-maintainers:
    - mdraw
    - albu
    - creafz
    - nrweir
    - ternaus
    - BloodAxe
